### This is a template of an issue template
### Lines marked by <<<..._LIST>>> need to be replaced by lists
### extracted from the corresponding EXFOR dictionaries
name: New Dataset
description: Add a new dataset to exfor
title: "[New Data]: "
labels: ["new data"]
projects: ["julia-sprenger/1"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Please provide the details of the new dataset below. Non applicable or available 
        information can be added / updated later.
  - type: markdown
    attributes:
      value: "# Bibliography"
  - type: input
    id: DOI
    attributes:
      label: Digital Object Identifier
      description: |
        The DOI reference of the data publication. When providing a DOI, subsequent fields
        (author, reference, year) do not need to be filled, but will be extracted automatically.
      placeholder: example 10.1103/PhysRevC.19.2127
    validations:
      required: false
  - type: input
    id: author
    attributes:
      label: Authors
      description: |
        Provide the author names in the following format: A.Smith,B.Brown,C.Johnson
      placeholder: example 10.1103/PhysRevC.19.2127
    validations:
      required: false  
  - type: dropdown
    id: reference_type
    attributes:
      label: Reference type
      description: What type is your reference?
      # TODO: This list of choices should be frequenly automatically updated from
      # https://github.com/IAEA-NDS/exfor_dictionary/blob/main/src/exfor_dictionary/latest.json or from
      # latest dicts files here: https://www-nds.iaea.org/public/exfor/backup/
      options:
<<<REFERENCE_TYPE_LIST>>>
      default: 7
    validations:
      required: false
  - type: dropdown
    id: journal
    attributes:
      label: Journal
      description: In case of a journal publication select the journal below
      # TODO: This list of choices should be frequenly automatically updated from
      # https://github.com/IAEA-NDS/exfor_dictionary/blob/main/src/exfor_dictionary/latest.json or from
      # latest dicts files here: https://www-nds.iaea.org/public/exfor/backup/
      options:
<<<JOURNAL_LIST>>>
        - Other (please update later on)
    validations:
      required: false
  - type: input
    id: volume
    attributes:
      label: Volume
      description: The volume number of the publication
      placeholder: example 10
    validations:
      required: false
  - type: input
    id: paper_number
    attributes:
      label: Paper number
      description: The number of the paper in the in the volume
      placeholder: example 3
    validations:
      required: false
  - type: input
    id: page_number
    attributes:
      label: Page number
      description: The page number on which the article begins
      placeholder: example 157
    validations:
      required: false
  - type: input
    id: year
    attributes:
      label: Year
      description: The year of reference publication
      placeholder: example 2019
    validations:
      required: false
  - type: dropdown
    id: institute
    attributes:
      label: Institute
      description: Which institute produced the data?
      # TODO: This list of choices should be frequenly automatically updated from
      # https://github.com/IAEA-NDS/exfor_dictionary/blob/main/src/exfor_dictionary/latest.json or from
      # latest dicts files here: https://www-nds.iaea.org/public/exfor/backup/
      options:
<<<INSTITUTE_LIST>>>
        - Other (please update later on)
    validations:
      required: false

# issue templating options

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
